version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: snipeit-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - snipeit-db-data:/var/lib/mysql

  snipeit:
    image: 448049798930.dkr.ecr.eu-west-2.amazonaws.com/snipeit:v8.3.6   # ✏️
    container_name: snipeit-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.snipeit
    ports:
      - "80:80"

  flask:
    image: 448049798930.dkr.ecr.eu-west-2.amazonaws.com/flask-middleware:latest   # ✏️
    container_name: snipeit-flask
    restart: unless-stopped
    env_file:
      - .env.flask
    depends_on:
      - snipeit

volumes:
  snipeit-db-data: